### ISSUE TITLE
Unable to remove all the extra images from the example

### ISSUE THREAD

**Issue by HimanshuMenon** [BotDanny/react-stacked-center-carousel#12] opened 2022-10-26 16:05 UTC
Hi, I am implementing this carousel but I am unable to remove all the extra images that I am getting in the Demo Code. I am unable to remove two extra images from the data array.

This is what my current data array looks like

```
export const data = [
  {
    cover:
      "https://d25s2jqw4qdf1e.cloudfront.net/a80c4ba3-6a04-45e3-baa6-29cfbae77dfb.webp?imwidth=3840",
    title: "Interstaller",
  },
  {
    cover:
      "https://d25s2jqw4qdf1e.cloudfront.net/70526bde-da54-4c34-91b6-eafbf6baeaff.webp?imwidth=3840",
    title: "Inception",
  },
  {
    cover:
      "https://d25s2jqw4qdf1e.cloudfront.net/c9aae31f-9a66-4f56-9aab-211d5201b8d9.webp?imwidth=3840",
    title: "Blade Runner 2049",
  },
  {
    cover:
      "https://d25s2jqw4qdf1e.cloudfront.net/b81c80fe-1d87-4ad1-bb20-87d32f3596a7.webp?imwidth=3840",
    title: "Icon man 3",
  },
  {
    cover: "https://images3.alphacoders.com/948/thumb-1920-948864.jpg",
    title: "Venom",
  },
  {
    cover: "https://images4.alphacoders.com/665/thumb-1920-665242.png",
    title: "One Punch Man",
  },
];

```
When I remove the last object from the data it gives me the error  Cannot read properties of undefined (reading 'cover')
I hope you guys could guide me on what I might be doing wrong.

**Comment by BotDanny** [comment] 2022-10-26 22:33
Hi, I am unable to reproduce your error. Can you provide a code sandbox link?

**Comment by BotDanny** [comment] 2022-10-27 19:59
Closing the issue for now, if you can reproduce it with a code sandbox link then feel free to re-open the issue

**Closed by BotDanny** 2022-10-27 19:59 UTC
